// Values.ts

export const chanceToGetSpellFromBonding = 0.01;

export const itemValues = {
    trap: { value: 100 },
    bonding: { value: 500 },
};
export const renownValues = {
    bonding: { maxRenown: 100, maxFailedRenown: -100 },
    detectedSpell: { failedRenown: -100 },
};

export const renownToWitchModifiers: IRenownLevels = {
    0: { max: 0.1, min: 0.05 },
    10: { max: 0.25, min: 0.1 },
    50: { max: 0.5, min: 0.1 },
    100: { max: 1.0, min: 1.0 },
    250: { max: 1.5, min: 1.5 },
    500: { max: 2, min: 2 },
};

export const renownToGoldModifiers: IRenownLevels = {
    0: { max: 0.05, min: 0.01 },
    10: { max: 0.1, min: 0.05 },
    50: { max: 0.25, min: 0.1 },
    100: { max: 0.5, min: 0.25 },
    250: { max: 0.75, min: 0.5 },
    500: { max: 1, min: 0.75 },
};

interface IRenownLevels {
    [key: string]: {
        max: number;
        min: number;
    };
}

export const renownLevelDivision: IRenownLevels = {
    0: { max: 9, min: 0 },
    10: { max: 49, min: 10 },
    50: { max: 99, min: 50 },
    100: { max: 249, min: 100 },
    250: { max: 499, min: 250 },
    500: { max: 750, min: 500 },
};
// Species
export const species: string[] = ["Human", "Feline", "Other"];

// Cat Variants
export const catVariants: TCatVariant[] = [
    "Tabby",
    "Siamese",
    "Persian",
    "Maine Coon",
    "Bengal",
    "Sphynx",
    "Ragdoll",
    "British Shorthair",
    "Abyssinian",
    "Scottish Fold",
];

type TCatVariantValues = {
    Tabby: { value: number; color: TCatColors[] };
    Siamese: { value: number; color: TCatColors[] };
    Persian: { value: number; color: TCatColors[] };
    "Maine Coon": { value: number; color: TCatColors[] };
    Bengal: { value: number; color: TCatColors[] };
    Sphynx: { value: number; color: TCatColors[] };
    Ragdoll: { value: number; color: TCatColors[] };
    "British Shorthair": { value: number; color: TCatColors[] };
    Abyssinian: { value: number; color: TCatColors[] };
    "Scottish Fold": { value: number; color: TCatColors[] };
};

export type TCatVariant = keyof TCatVariantValues;

export const catVariantValues: TCatVariantValues = {
    Tabby: { value: 7, color: ["orange", "greytone"] },
    Siamese: { value: 25, color: ["white"] },
    Persian: { value: 30, color: ["white", "grey", "black", "orange"] },
    "Maine Coon": {
        value: 15,
        color: ["white", "orange", "greytone", "black"],
    },
    Bengal: { value: 45, color: ["orange", "greytone"] },
    Sphynx: { value: 20, color: ["pink", "grey", "black", "white"] },
    Ragdoll: { value: 35, color: ["white"] },
    "British Shorthair": {
        value: 15,
        color: ["black", "grey", "white", "orange"],
    },
    Abyssinian: { value: 40, color: ["orange"] },
    "Scottish Fold": {
        value: 25,
        color: ["grey", "white", "greytone", "black", "orange"],
    },
};

type TCatColors = "black" | "orange" | "greytone" | "white" | "grey" | "pink";

export const catVariantsByColor = (color: TCatColors) =>
    Object.keys(catVariantValues).filter((cat) =>
        catVariantValues[cat as TCatVariant].color.includes(color)
    );

export const getBlackCatVariants = () =>
    Object.keys(catVariantValues).filter((cat) =>
        catVariantValues[cat as TCatVariant].color.includes("black")
    );

// Witch Traits
export const allTraits: string[] = [
    "affectionate",
    "calm",
    "charming",
    "clever",
    "independent",
    "mischievous",
    "playful",
    "possessive",
    "reclusive",
    "stubborn",
    "vocal",
    "agressive",
    "thoughtful",
    "short fused",
    "defiant",
    "greedy",
];

// Names for Cats
export const catNames: string[] = [
    "Alioth",
    "Apophis",
    "Arcana",
    "Astaroth",
    "Baba",
    "Bannik",
    "Bastet",
    "Belladonna",
    "Beliaal",
    "Bingus",
    "Blackie",
    "Boginka",
    "Brimstone",
    "Cernunnos",
    "Cobweb",
    "Cossack",
    "Circe",
    "Dark One",
    "Domovoi",
    "Draco",
    "Dusk",
    "Djinni",
    "Echo",
    "Eclipse",
    "Fenrir",
    "Freya",
    "Gargoyle",
    "Goblin",
    "Grimoire",
    "Hecate",
    "Hex",
    "Hypnos",
    "Isolde",
    "Jinx",
    "Jormungandr",
    "Jove",
    "Kikimora",
    "Kitsune",
    "Leshy",
    "Lucifer",
    "Luna",
    "Mab",
    "Maw",
    "Mingus",
    "Mittens",
    "Morana",
    "Morpheus",
    "Morgana",
    "Nebula",
    "Nimue",
    "Nyx",
    "Obsidian",
    "Oliver",
    "Omen",
    "Onyx",
    "Orpheus",
    "Pandora",
    "Persephone",
    "Phobos",
    "Pixie",
    "Puck",
    "Pudge",
    "Quicksilver",
    "Raven",
    "Rook",
    "Rusalka",
    "Sable",
    "Salem",
    "Selene",
    "Seth",
    "Siren",
    "Stian",
    "Sylph",
    "Talon",
    "Undine",
    "Vesper",
    "Vila",
    "Void",
    "Voodoo",
    "Wraith",
    "Zorya",
];

export const witchFirstNames = [
    "Adeline",
    "Aelin",
    "Agatha",
    "Allegra",
    "Alondra",
    "Amity",
    "Aurora",
    "Aurelia",
    "Avery",
    "Belladonna",
    "Billie",
    "Borghilde",
    "Bronwyn",
    "Brione",
    "Calantha",
    "Calliope",
    "Cassandra",
    "Ceres",
    "Clementine",
    "Cleo",
    "Cosette",
    "Constance",
    "Dea",
    "Donna",
    "Elowen",
    "Electra",
    "Elspeth",
    "Etta",
    "Eufemia",
    "Egeria",
    "Fern",
    "Fillippa",
    "Fawn",
    "Fleur",
    "Freya",
    "Francesca",
    "Ginevra",
    "Georgianna",
    "Gladys",
    "Griselda",
    "Gwynne",
    "Gwendolyn",
    "Halimeda",
    "Hazel",
    "Heather",
    "Helga",
    "Hestia",
    "Helenore",
    "Hyacinth",
    "Iris",
    "Isis",
    "Isobel",
    "Jeanne",
    "Jennifer",
    "Juniper",
    "Kyria",
    "Laetitia",
    "Larissa",
    "Lexa",
    "Lissandra",
    "Lilith",
    "Lux",
    "Lyra",
    "Maribel",
    "Minerva",
    "Morticia",
    "Moxie",
    "Nebula",
    "Odette",
    "Olga",
    "Olive",
    "Orelia",
    "Perspicacity",
    "Piper",
    "Prudence",
    "Qaeda",
    "Quintessa",
    "Raven",
    "Rowan",
    "Rue",
    "Salome",
    "Scarlet",
    "Seraphina",
    "Sherah",
    "Shoggoth",
    "Stacy",
    "Stella",
    "Tallulah",
    "Thea",
    "Theofania",
    "Tirza",
    "Ursula",
    "Vandelia",
    "Vashti",
    "Verity",
    "Vesper",
    "Vivianne",
    "Winnie",
    "Wisteria",
    "Xanthe",
    "Xiomara",
    "Zelia",
    "Zephyra",
    "Zelda",
];

// Surnames for Witches (REPLACED)
export const witchSurNames = [
    "Addicock",
    "Amondsham",
    "Atherton",
    "Barrentine",
    "Basset",
    "Ballard",
    "Barnaby",
    "Beauchamp",
    "Beaumont",
    "Beauclair",
    "Berdwell",
    "Bexley",
    "Blackwood",
    "Blodwell",
    "Blount",
    "Botteler",
    "Braunstone",
    "Brecknock",
    "Brassie",
    "Brook",
    "Bulkeley",
    "Bulstrode",
    "Burgoyne",
    "Buslingthorpe",
    "Chauncey",
    "Chatwyn",
    "Chilton",
    "Cheddar",
    "Cockayne",
    "Coggshall",
    "Cossington",
    "Culpepper",
    "Dagworth",
    "Damsell",
    "Davenport",
    "Devereaux",
    "Diddle",
    "Dimmock",
    "Dogmersfield",
    "Dusteby",
    "Ellison",
    "Etton",
    "Finch",
    "Flexney",
    "Fortescue",
    "Garwood",
    "Gardner",
    "Gavell",
    "Gaylord",
    "Goldwell",
    "Goodrick",
    "Halebourne",
    "Hancock",
    "Harper",
    "Harleston",
    "Hastings",
    "Higden",
    "Killigrew",
    "Kirkeby",
    "Latham",
    "Leventhorpe",
    "Lestrange",
    "Lodding",
    "Lovelace",
    "Malster",
    "Mapilton",
    "Marcheford",
    "Markeley",
    "Massingberd",
    "Mauntell",
    "McSpooky",
    "Menzies",
    "Motesfont",
    "Mowfurth",
    "Mugg",
    "Neburgh",
    "Newdegate",
    "Nightingale",
    "Norbury",
    "Outlawe",
    "Oxenbrigg",
    "Pemberton",
    "Pelletoot",
    "Penhallick",
    "Petham",
    "Piggott",
    "Pinncock",
    "Polsted",
    "Polton",
    "Pursglove",
    "Radcliffe",
    "Risley",
    "Roper",
    "Saltonstall",
    "Saintjohn",
    "Sackville",
    "Selwyn",
    "Sinclair",
    "Sibbell",
    "Stoddeley",
    "Strangewayes",
    "Strelley",
    "Sweetecok",
    "Tabard",
    "Tedcastle",
    "Thorn",
    "Thornburgh",
    "Thursby",
    "Tiploft",
    "Tibbord",
    "Topsfield",
    "Torrington",
    "Trump",
    "Tregonwell",
    "Twarby",
    "Ufford",
    "Urswick",
    "Underwood",
    "Vintner",
    "Waldegrave",
    "Walrond",
    "Warbulton",
    "Wexcombe",
    "Whitewood",
    "Whitton",
    "Wightman",
    "Winthrop",
    "Wistring",
    "Worsley",
    "Wreke",
];

// Witch Vocations
export const witchVocations = [
    "Alchemist",
    "Diviner",
    "Enchantress",
    "Herbalist",
    "Necromancer",
    "Satanist",
];

// Witchcraft Approaches (NEW)
export const witchApproaches = [
    ["Animist", "Materialist"],
    ["Authoritarian", "Egalitarian"],
    ["Exploratory", "Scholastic"],
    ["Extremist", "Moderate"],
    ["Purist", "Syncretic"],
];

// Default Abilities for Cats
export const defaultCatAbilities = {
    reflex: 40,
    balance: 40,
    speed: 40,
    vision: 40,
    hearing: 40,
    smell: 40,
    taste: 40,
    memory: 40,
    intuition: 40,
    magicinsight: 40,
    patience: 40,
    boldness: 40,
    mischief: 40,
    sneaking: 40,
    hiding: 40,
    strength: 40,
    grip: 40,
    endurance: 40,
    magicresistance: 40,
    luck: 40,
};

// Default Abilities for Witches        NEEDS REWORK
export const defaultWitchAbilities = {
    reflex: 40,
    balance: 40,
    speed: 40,
    vision: 40,
    hearing: 40,
    smell: 40,
    taste: 40,
    memory: 40,
    intuition: 40,
    magicinsight: 40,
    patience: 40,
    boldness: 40,
    mischief: 40,
    sneaking: 40,
    hiding: 40,
    strength: 40,
    grip: 40,
    endurance: 40,
    magicresistance: 40,
    luck: 40,
};

export const defaultGuardianAbilities = {};
