// Values.ts

export const itemValues = {
  trap: { value: 10 },
};

// Species
export const species: string[] = ["Human", "Feline", "Other"];

export type TCatVariants =
  | "Black"
  | "Tabby"
  | "Siamese"
  | "Persian"
  | "Maine Coon"
  | "Bengal"
  | "Sphynx"
  | "Ragdoll"
  | "British Shorthair"
  | "Abyssinian"
  | "Scottish Fold";
// Cat Variants
export const catVariants = [
  "Black",
  "Tabby",
  "Siamese",
  "Persian",
  "Maine Coon",
  "Bengal",
  "Sphynx",
  "Ragdoll",
  "British Shorthair",
  "Abyssinian",
  "Scottish Fold",
];

export const catVariantValues = {
  Black: { value: 10, color: ["black"] },
  Tabby: { value: 7, color: ["orange", "greytone"] },
  Siamese: { value: 25, color: ["white"] },
  Persian: { value: 30, color: ["white", "grey", "black", "orange"] },
  "Maine Coon": { value: 15, color: ["white", "ginger", "greytone", "black"] },
  Bengal: { value: 45, color: ["orange", "greytone"] },
  Sphynx: { value: 20, color: ["pink", "grey", "black", "white"] },
  Ragdoll: { value: 35, color: ["white"] },
  "British Shorthair": {
    value: 15,
    color: ["black", "grey", "white", "orange"],
  },
  Abyssinian: { value: 40, color: ["orange"] },
  "Scottish Fold": {
    value: 25,
    color: ["grey", "white", "greystone", "black", "orange"],
  },
};

// Cat Traits
export const catTraits = [
  "playful",
  "curious",
  "affectionate",
  "independent",
  "shy",
  "vocal",
  "lazy",
  "friendly",
  "aggressive",
  "intelligent",
];

// Cat Traits Reworked    (Are we missing Playful or Mischievous?)
// export const catTraitsNew: string[] = [
//   ["Active", "Lazy"],
//   ["Curious", "Shy"],
//   ["Cunning", "Derpy"],
//   ["Impulsive", "Anxious"],
//   ["Sweet", "Mischievous"],
//   ["Vocal", "Quiet"],
// ];

// Cat Traits Reworked    (Are we missing Playful or Mischievous?)
// export const catTraitsNew: string[] = [
//   ["Active", "Lazy"],
//   ["Curious", "Shy"],
//   ["Cunning", "Derpy"],
//   ["Impulsive", "Anxious"],
//   ["Sweet", "Mischievous"],
//   ["Vocal", "Quiet"],
// ];

// Witch Traits
export const witchTraits: string[] = [
  "vindictive",
  "paranoid",
  "lustful",
  "wise",
  "mysterious",
  "manipulative",
  "charismatic",
  "secretive",
  "ambitious",
  "cunning",
];

// Names for Cats
export const catNames: string[] = [
  "Alioth",
  "Astaroth",
  "Artemis",
  "Banshee",
  "Bastet",
  "Belladonna",
  "Beliaal",
  "Brimstone",
  "Cernunnos",
  "Cobweb",
  "Circe",
  "Draco",
  "Dusk",
  "Djinni",
  "Echo",
  "Eclipse",
  "Fenrir",
  "Freya",
  "Gargoyle",
  "Goblin",
  "Grimoire",
  "Hecate",
  "Hex",
  "Hypnos",
  "Isolde",
  "Jinx",
  "Jormungandr",
  "Jove",
  "Kitsune",
  "Lucifer",
  "Luna",
  "Mab",
  "Mittens",
  "Morpheus",
  "Morgana",
  "Nebula",
  "Nimue",
  "Nyx",
  "Obsidian",
  "Oliver",
  "Omen",
  "Onyx",
  "Pandora",
  "Persephone",
  "Phobos",
  "Pixie",
  "Puck",
  "Pudge",
  "Quicksilver",
  "Raven",
  "Rook",
  "Sable",
  "Salem",
  "Selene",
  "Seth",
  "Siren",
  "Sylph",
  "Talon",
  "Undine",
  "Vesper",
  "Voodoo",
  "Wraith",
];

export const witchFirstNames = [
  "Adeline",
  "Aelin",
  "Agatha",
  "Allegra",
  "Alondra",
  "Amity",
  "Aurora",
  "Aurelia",
  "Avery",
  "Belladonna",
  "Billie",
  "Borghilde",
  "Bronwyn",
  "Brione",
  "Calantha",
  "Calliope",
  "Cassandra",
  "Ceres",
  "Clementine",
  "Cleo",
  "Cosette",
  "Constance",
  "Dea",
  "Donna",
  "Elowen",
  "Electra",
  "Elspeth",
  "Etta",
  "Eufemia",
  "Egeria",
  "Fern",
  "Fillippa",
  "Fawn",
  "Fleur",
  "Freya",
  "Francesca",
  "Ginevra",
  "Georgianna",
  "Gladys",
  "Griselda",
  "Gwynne",
  "Gwendolyn",
  "Halimeda",
  "Hazel",
  "Heather",
  "Helga",
  "Hestia",
  "Helenore",
  "Hyacinth",
  "Iris",
  "Isis",
  "Isobel",
  "Jeanne",
  "Jennifer",
  "Juniper",
  "Kyria",
  "Laetitia",
  "Larissa",
  "Lexa",
  "Lissandra",
  "Lilith",
  "Lux",
  "Lyra",
  "Maribel",
  "Minerva",
  "Morticia",
  "Moxie",
  "Nebula",
  "Odette",
  "Olga",
  "Olive",
  "Orelia",
  "Perspicacity",
  "Piper",
  "Prudence",
  "Qaeda",
  "Quintessa",
  "Raven",
  "Rowan",
  "Rue",
  "Salome",
  "Scarlet",
  "Seraphina",
  "Sherah",
  "Shoggoth",
  "Stacy",
  "Stella",
  "Tallulah",
  "Thea",
  "Theofania",
  "Tirza",
  "Ursula",
  "Vandelia",
  "Vashti",
  "Verity",
  "Vesper",
  "Vivianne",
  "Winnie",
  "Wisteria",
  "Xanthe",
  "Xiomara",
  "Zelia",
  "Zephyra",
  "Zelda",
];

// Surnames for Witches (REPLACED)
export const witchSurNames = [
  "Addicock",
  "Amondsham",
  "Atherton",
  "Barrentine",
  "Basset",
  "Ballard",
  "Barnaby",
  "Beauchamp",
  "Beaumont",
  "Beauclair",
  "Berdwell",
  "Bexley",
  "Blackwood",
  "Blodwell",
  "Blount",
  "Botteler",
  "Braunstone",
  "Brecknock",
  "Brassie",
  "Brook",
  "Bulkeley",
  "Bulstrode",
  "Burgoyne",
  "Buslingthorpe",
  "Chauncey",
  "Chatwyn",
  "Chilton",
  "Cheddar",
  "Cockayne",
  "Coggshall",
  "Cossington",
  "Culpepper",
  "Dagworth",
  "Damsell",
  "Davenport",
  "Devereaux",
  "Diddle",
  "Dimmock",
  "Dogmersfield",
  "Dusteby",
  "Ellison",
  "Etton",
  "Finch",
  "Flexney",
  "Fortescue",
  "Garwood",
  "Gardner",
  "Gavell",
  "Gaylord",
  "Goldwell",
  "Goodrick",
  "Halebourne",
  "Hancock",
  "Harper",
  "Harleston",
  "Hastings",
  "Higden",
  "Killigrew",
  "Kirkeby",
  "Latham",
  "Leventhorpe",
  "Lestrange",
  "Lodding",
  "Lovelace",
  "Malster",
  "Mapilton",
  "Marcheford",
  "Markeley",
  "Massingberd",
  "Mauntell",
  "McSpooky",
  "Menzies",
  "Motesfont",
  "Mowfurth",
  "Mugg",
  "Neburgh",
  "Newdegate",
  "Nightingale",
  "Norbury",
  "Outlawe",
  "Oxenbrigg",
  "Pemberton",
  "Pelletoot",
  "Penhallick",
  "Petham",
  "Piggott",
  "Pinncock",
  "Polsted",
  "Polton",
  "Pursglove",
  "Radcliffe",
  "Risley",
  "Roper",
  "Saltonstall",
  "Saintjohn",
  "Sackville",
  "Selwyn",
  "Sinclair",
  "Sibbell",
  "Stoddeley",
  "Strangewayes",
  "Strelley",
  "Sweetecok",
  "Tabard",
  "Tedcastle",
  "Thorn",
  "Thornburgh",
  "Thursby",
  "Tiploft",
  "Tibbord",
  "Topsfield",
  "Torrington",
  "Trump",
  "Tregonwell",
  "Twarby",
  "Ufford",
  "Urswick",
  "Underwood",
  "Vintner",
  "Waldegrave",
  "Walrond",
  "Warbulton",
  "Wexcombe",
  "Whitewood",
  "Whitton",
  "Wightman",
  "Winthrop",
  "Wistring",
  "Worsley",
  "Wreke",
];

// Witch Vocations
export const witchVocations = [
  "Alchemist",
  "Diviner",
  "Enchantress",
  "Herbalist",
  "Necromancer",
  "Satanist",
];

// Witchcraft Approaches (NEW)
export const witchApproaches = [
  ["Animist", "Materialist"],
  ["Authoritarian", "Egalitarian"],
  ["Exploratory", "Scholastic"],
  ["Extremist", "Moderate"],
  ["Purist", "Syncretic"],
];

// Default Abilities for Cats
export const defaultCatAbilities = {
  reflex: 40,
  balance: 40,
  speed: 40,
  vision: 40,
  hearing: 40,
  smell: 40,
  taste: 40,
  memory: 40,
  intuition: 40,
  magicinsight: 40,
  patience: 40,
  boldness: 40,
  mischief: 40,
  sneaking: 40,
  hiding: 40,
  strength: 40,
  grip: 40,
  endurance: 40,
  magicresistance: 40,
  luck: 40,
};

// Default Abilities for Witches        NEEDS REWORK
export const defaultWitchAbilities = {
  reflex: 40,
  balance: 40,
  speed: 40,
  vision: 40,
  hearing: 40,
  smell: 40,
  taste: 40,
  memory: 40,
  intuition: 40,
  magicinsight: 40,
  patience: 40,
  boldness: 40,
  mischief: 40,
  sneaking: 40,
  hiding: 40,
  strength: 40,
  grip: 40,
  endurance: 40,
  magicresistance: 40,
  luck: 40,
};

export const defaultGuardianAbilities = {};
