// Values.ts

// Species
export const species: string[] = [
  "Human",
  "Feline",
  "Avian",
  "Canine",
  "Reptilian",
  "Daimon",
  "Demon",
  "Devil",
  "Goat",
  "Ghost",
  "Faerie",
  "Pixie",
  "Troll",
  "Construct",
];

// Cat Variants
export const catVariants: string[] = [
  "Black",
  "Tabby",
  "Siamese",
  "Persian",
  "Maine Coon",
  "Bengal",
  "Sphynx",
  "Ragdoll",
  "British Shorthair",
  "Abyssinian",
  "Scottish Fold",
];

// Cat Traits
export const catTraits: string[] = [
  "playful",
  "curious",
  "affectionate",
  "independent",
  "shy",
  "vocal",
  "lazy",
  "friendly",
  "aggressive",
  "intelligent",
];

// Witch Traits
export const witchTraits: string[] = [
  "vindictive",
  "paranoid",
  "lustful",
  "wise",
  "mysterious",
  "manipulative",
  "charismatic",
  "secretive",
  "ambitious",
  "cunning",
];

// Witch Variants
export const witchVariants: string[] = [
  "Healer",
  "Necromancer",
  "Elementalist",
  "Diviner",
  "Alchemist",
  "Herbalist",
  "Satanic",
  "Celestial",
  "Green Witch",
];

// Names for Cats
export const catNames: string[] = [
  "Mittens",
  "Beliaal",
  "Lucifer",
  "Oliver",
  "Luna",
  "Jove",
  "Seth",
  "Pudge",
  "Phobos",
  "Alioth",
  "Djinni",
  "Gary",
];

export const witchFirstNames = [
  "Adeline",
  "Aelin",
  "Agatha",
  "Allegra",
  "Alondra",
  "Amity",
  "Aurora",
  "Aurelia",
  "Avery",
  "Belladonna",
  "Billie",
  "Borghilde",
  "Bronwyn",
  "Brione",
  "Calantha",
  "Calliope",
  "Cassandra",
  "Ceres",
  "Clementine",
  "Cleo",
  "Cosette",
  "Constance",
  "Dea",
  "Donna",
  "Elowen",
  "Electra",
  "Elspeth",
  "Etta",
  "Eufemia",
  "Egeria",
  "Fern",
  "Fillippa",
  "Fawn",
  "Fleur",
  "Freya",
  "Francesca",
  "Ginevra",
  "Georgianna",
  "Gladys",
  "Griselda",
  "Gwynne",
  "Gwendolyn",
  "Halimeda",
  "Hazel",
  "Heather",
  "Helga",
  "Hestia",
  "Helenore",
  "Hyacinth",
  "Iris",
  "Isis",
  "Isobel",
  "Jeanne",
  "Jennifer",
  "Juniper",
  "Kyria",
  "Laetitia",
  "Larissa",
  "Lexa",
  "Lissandra",
  "Lilith",
  "Lux",
  "Lyra",
  "Maribel",
  "Minerva",
  "Morticia",
  "Moxie",
  "Nebula",
  "Odette",
  "Olga",
  "Olive",
  "Orelia",
  "Perspicacity",
  "Piper",
  "Prudence",
  "Qaeda",
  "Quintessa",
  "Raven",
  "Rowan",
  "Rue",
  "Salome",
  "Scarlet",
  "Seraphina",
  "Sherah",
  "Shoggoth",
  "Stacy",
  "Stella",
  "Tallulah",
  "Thea",
  "Theofania",
  "Tirza",
  "Ursula",
  "Vandelia",
  "Vashti",
  "Verity",
  "Vesper",
  "Vivianne",
  "Winnie",
  "Wisteria",
  "Xanthe",
  "Xiomara",
  "Zelia",
  "Zephyra",
  "Zelda",
];

// Surnames for Witches (REPLACED)
export const witchSurNames = [
  "Addicock",
  "Amondsham",
  "Atherton",
  "Barrentine",
  "Basset",
  "Ballard",
  "Barnaby",
  "Beauchamp",
  "Beaumont",
  "Beauclair",
  "Berdwell",
  "Bexley",
  "Blackwood",
  "Blodwell",
  "Blount",
  "Botteler",
  "Braunstone",
  "Brecknock",
  "Brassie",
  "Brook",
  "Bulkeley",
  "Bulstrode",
  "Burgoyne",
  "Buslingthorpe",
  "Chauncey",
  "Chatwyn",
  "Chilton",
  "Cheddar",
  "Cockayne",
  "Coggshall",
  "Cossington",
  "Culpepper",
  "Dagworth",
  "Damsell",
  "Davenport",
  "Devereaux",
  "Diddle",
  "Dimmock",
  "Dogmersfield",
  "Dusteby",
  "Ellison",
  "Etton",
  "Finch",
  "Flexney",
  "Fortescue",
  "Garwood",
  "Gardner",
  "Gavell",
  "Gaylord",
  "Goldwell",
  "Goodrick",
  "Halebourne",
  "Hancock",
  "Harper",
  "Harleston",
  "Hastings",
  "Higden",
  "Killigrew",
  "Kirkeby",
  "Latham",
  "Leventhorpe",
  "Lestrange",
  "Lodding",
  "Lovelace",
  "Malster",
  "Mapilton",
  "Marcheford",
  "Markeley",
  "Massingberd",
  "Mauntell",
  "McSpooky",
  "Menzies",
  "Motesfont",
  "Mowfurth",
  "Mugg",
  "Neburgh",
  "Newdegate",
  "Nightingale",
  "Norbury",
  "Outlawe",
  "Oxenbrigg",
  "Pemberton",
  "Pelletoot",
  "Penhallick",
  "Petham",
  "Piggott",
  "Pinncock",
  "Polsted",
  "Polton",
  "Pursglove",
  "Radcliffe",
  "Risley",
  "Roper",
  "Saltonstall",
  "Saintjohn",
  "Sackville",
  "Selwyn",
  "Sinclair",
  "Sibbell",
  "Stoddeley",
  "Strangewayes",
  "Strelley",
  "Sweetecok",
  "Tabard",
  "Tedcastle",
  "Thorn",
  "Thornburgh",
  "Thursby",
  "Tiploft",
  "Tibbord",
  "Topsfield",
  "Torrington",
  "Trump",
  "Tregonwell",
  "Twarby",
  "Ufford",
  "Urswick",
  "Underwood",
  "Vintner",
  "Waldegrave",
  "Walrond",
  "Warbulton",
  "Wexcombe",
  "Whitewood",
  "Whitton",
  "Wightman",
  "Winthrop",
  "Wistringt",
  "Worsley",
  "Wreke",
  "Yornold",
];

// Witch Domains (NEW)
export const witchDomains = [
  "Adoratrice",
  "Anchoress",
  "Arcanist",
  "Bruja",
  "Chthonian",
  "Crone",
  "Diviner",
  "Druid",
  "Enchantress",
  "Fungalist",
  "Gnostic",
  "Hag",
  "Hedge Witch",
  "Hekatean",
  "Hellenic",
  "Herbalist",
  "Medium",
  "Moon Priestess",
  "Nahuatl",
  "Necromancer",
  "Harpy",
  "Oracle",
  "Satanist",
  "Seidwoman",
  "Sethian",
  "Summoner",
  "Supremacist",
  "Tantrik",
  "Voodoo Priestess",
  "Wiccan",
  "Mutilant",
  "Galvanist",
  "Seancer",
  "Maledictrice",
  "Goetic",
  "Strega",
];

// Witch Approaches (NEW)
export const witchApproaches = [
  ["Orthodox", "Liberal"],
  ["Syncretic", "Segregationist"],
  ["Rational", "Empirical"],
  ["Moderate", "Extremist"],
  ["Inclusionary", "Exclusionary"],
  ["Realist", "Idealist"],
  ["Determinist", "Volitionist"],
  ["Ambitious", "Content"],
  ["Dogmatic", "Iconoclastic"],
  ["Scholastic", "Experiential"],
  ["Theoretical", "Applied"],
  ["Legalist", "Mystic"],
  ["Ascetic", "Indulgent"],
  ["Prudish", "Wanton"],
  ["Hedonist", "Fuddy-Duddy"],
];

// Default Abilities for Cats
export const defaultCatAbilities = {
  reflex: 40,
  balance: 40,
  speed: 40,
  vision: 40,
  hearing: 40,
  smell: 40,
  taste: 40,
  memory: 40,
  intuition: 40,
  magicinsight: 40,
  patience: 40,
  boldness: 40,
  mischief: 40,
  sneaking: 40,
  hiding: 40,
  strength: 40,
  grip: 40,
  endurance: 40,
  magicresistance: 40,
  luck: 40,
};

// Default Abilities for Witches
export const defaultWitchAbilities = {
  reflex: 40,
  balance: 40,
  speed: 40,
  vision: 40,
  hearing: 40,
  smell: 40,
  taste: 40,
  memory: 40,
  intuition: 40,
  magicinsight: 40,
  patience: 40,
  boldness: 40,
  mischief: 40,
  sneaking: 40,
  hiding: 40,
  strength: 40,
  grip: 40,
  endurance: 40,
  magicresistance: 40,
  luck: 40,
};
